### ISSUE TITLE
cat in the picture is NOT el gato

### ISSUE THREAD

**Issue by MechaXYZ** [OrangeCash090/Roblox-3D-Engine#1]
it looks like floppa!! how could you do this FBXImportGeneric!!! 😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡
![doggo](https://github.com/OrangeCash090/Roblox-3D-Engine/assets/93439705/228afeb5-4ce7-4542-85f7-ee5c4ced1279)

**Comment by TheTopHat26** [comment]
I cannot believe this

**Comment by Joe0132134** [comment]
fr

**Comment by OrangeCash090** [comment]
solved
